backend:
  name: github
  repo: jwknz/JWKAstrostart
  branch: content

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", value_type: "int", default: 100 }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", value_type: "int", default: 100 }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }